server:
  port: 8083
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/post-service?authSource=admin
jwt:
  signerKey: "s+KlA43TK3WxkiC1/FNogayrp2ARR3xMary3dTM3md8t7ihsPKNAkA350Og9YWZD"
  valid-duration: 20
  refreshable-duration: 120

app:
  services:
    profile:
      url: http//localhost:8081/profile